<?php

use App\Models\Country;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (!Schema::hasTable('countries')) {
            $countryJson = [
                ["name"=>"Afghanistan","mobile_code"=>"+93","code"=>"AF"],
                ["name"=>"Albania","mobile_code"=>"+355","code"=>"AL"],
                ["name"=>"Algeria","mobile_code"=>"+213","code"=>"DZ"],
                ["name"=>"AmericanSamoa","mobile_code"=>"+1 684","code"=>"AS"],
                ["name"=>"Andorra","mobile_code"=>"+376","code"=>"AD"],
                ["name"=>"Angola","mobile_code"=>"+244","code"=>"AO"],
                ["name"=>"Anguilla","mobile_code"=>"+1 264","code"=>"AI"],
                ["name"=>"Antarctica","mobile_code"=>"+672","code"=>"AQ"],
                ["name"=>"Antigua and Barbuda","mobile_code"=>"+1268","code"=>"AG"],
                ["name"=>"Argentina","mobile_code"=>"+54","code"=>"AR"],
                ["name"=>"Armenia","mobile_code"=>"+374","code"=>"AM"],
                ["name"=>"Aruba","mobile_code"=>"+297","code"=>"AW"],
                ["name"=>"Australia","mobile_code"=>"+61","code"=>"AU"],
                ["name"=>"Austria","mobile_code"=>"+43","code"=>"AT"],
                ["name"=>"Azerbaijan","mobile_code"=>"+994","code"=>"AZ"],
                ["name"=>"Bahamas","mobile_code"=>"+1 242","code"=>"BS"],
                ["name"=>"Bahrain","mobile_code"=>"+973","code"=>"BH"],
                ["name"=>"Bangladesh","mobile_code"=>"+880","code"=>"BD"],
                ["name"=>"Barbados","mobile_code"=>"+1 246","code"=>"BB"],
                ["name"=>"Belarus","mobile_code"=>"+375","code"=>"BY"],
                ["name"=>"Belgium","mobile_code"=>"+32","code"=>"BE"],
                ["name"=>"Belize","mobile_code"=>"+501","code"=>"BZ"],
                ["name"=>"Benin","mobile_code"=>"+229","code"=>"BJ"],
                ["name"=>"Bermuda","mobile_code"=>"+1 441","code"=>"BM"],
                ["name"=>"Bhutan","mobile_code"=>"+975","code"=>"BT"],
                ["name"=>"Bolivia, Plurinational State of","mobile_code"=>"+591","code"=>"BO"],
                ["name"=>"Bosnia and Herzegovina","mobile_code"=>"+387","code"=>"BA"],
                ["name"=>"Botswana","mobile_code"=>"+267","code"=>"BW"],
                ["name"=>"Brazil","mobile_code"=>"+55","code"=>"BR"],
                ["name"=>"British Indian Ocean Territory","mobile_code"=>"+246","code"=>"IO"],
                ["name"=>"Brunei Darussalam","mobile_code"=>"+673","code"=>"BN"],
                ["name"=>"Bulgaria","mobile_code"=>"+359","code"=>"BG"],
                ["name"=>"Burkina Faso","mobile_code"=>"+226","code"=>"BF"],
                ["name"=>"Burundi","mobile_code"=>"+257","code"=>"BI"],
                ["name"=>"Cambodia","mobile_code"=>"+855","code"=>"KH"],
                ["name"=>"Cameroon","mobile_code"=>"+237","code"=>"CM"],
                ["name"=>"Canada","mobile_code"=>"+1","code"=>"CA"],
                ["name"=>"Cape Verde","mobile_code"=>"+238","code"=>"CV"],
                ["name"=>"Cayman Islands","mobile_code"=>"+ 345","code"=>"KY"],
                ["name"=>"Central African Republic","mobile_code"=>"+236","code"=>"CF"],
                ["name"=>"Chad","mobile_code"=>"+235","code"=>"TD"],
                ["name"=>"Chile","mobile_code"=>"+56","code"=>"CL"],
                ["name"=>"China","mobile_code"=>"+86","code"=>"CN"],
                ["name"=>"Christmas Island","mobile_code"=>"+61","code"=>"CX"],
                ["name"=>"Cocos (Keeling) Islands","mobile_code"=>"+61","code"=>"CC"],
                ["name"=>"Colombia","mobile_code"=>"+57","code"=>"CO"],
                ["name"=>"Comoros","mobile_code"=>"+269","code"=>"KM"],
                ["name"=>"Congo","mobile_code"=>"+242","code"=>"CG"],
                ["name"=>"Congo, The Democratic Republic of the","mobile_code"=>"+243","code"=>"CD"],
                ["name"=>"Cook Islands","mobile_code"=>"+682","code"=>"CK"],
                ["name"=>"Costa Rica","mobile_code"=>"+506","code"=>"CR"],
                ["name"=>"Cote d\"Ivoire","mobile_code"=>"+225","code"=>"CI"],
                ["name"=>"Croatia","mobile_code"=>"+385","code"=>"HR"],
                ["name"=>"Cuba","mobile_code"=>"+53","code"=>"CU"],
                ["name"=>"Cyprus","mobile_code"=>"+357","code"=>"CY"],
                ["name"=>"Czech Republic","mobile_code"=>"+420","code"=>"CZ"],
                ["name"=>"Denmark","mobile_code"=>"+45","code"=>"DK"],
                ["name"=>"Djibouti","mobile_code"=>"+253","code"=>"DJ"],
                ["name"=>"Dominica","mobile_code"=>"+1 767","code"=>"DM"],
                ["name"=>"Dominican Republic","mobile_code"=>"+1 849","code"=>"DO"],
                ["name"=>"Ecuador","mobile_code"=>"+593","code"=>"EC"],
                ["name"=>"Egypt","mobile_code"=>"+20","code"=>"EG"],
                ["name"=>"El Salvador","mobile_code"=>"+503","code"=>"SV"],
                ["name"=>"Equatorial Guinea","mobile_code"=>"+240","code"=>"GQ"],
                ["name"=>"Eritrea","mobile_code"=>"+291","code"=>"ER"],
                ["name"=>"Estonia","mobile_code"=>"+372","code"=>"EE"],
                ["name"=>"Ethiopia","mobile_code"=>"+251","code"=>"ET"],
                ["name"=>"Falkland Islands (Malvinas)","mobile_code"=>"+500","code"=>"FK"],
                ["name"=>"Faroe Islands","mobile_code"=>"+298","code"=>"FO"],
                ["name"=>"Fiji","mobile_code"=>"+679","code"=>"FJ"],
                ["name"=>"Finland","mobile_code"=>"+358","code"=>"FI"],
                ["name"=>"France","mobile_code"=>"+33","code"=>"FR"],
                ["name"=>"French Guiana","mobile_code"=>"+594","code"=>"GF"],
                ["name"=>"French Polynesia","mobile_code"=>"+689","code"=>"PF"],
                ["name"=>"Gabon","mobile_code"=>"+241","code"=>"GA"],
                ["name"=>"Gambia","mobile_code"=>"+220","code"=>"GM"],
                ["name"=>"Georgia","mobile_code"=>"+995","code"=>"GE"],
                ["name"=>"Germany","mobile_code"=>"+49","code"=>"DE"],
                ["name"=>"Ghana","mobile_code"=>"+233","code"=>"GH"],
                ["name"=>"Gibraltar","mobile_code"=>"+350","code"=>"GI"],
                ["name"=>"Greece","mobile_code"=>"+30","code"=>"GR"],
                ["name"=>"Greenland","mobile_code"=>"+299","code"=>"GL"],
                ["name"=>"Grenada","mobile_code"=>"+1 473","code"=>"GD"],
                ["name"=>"Guadeloupe","mobile_code"=>"+590","code"=>"GP"],
                ["name"=>"Guam","mobile_code"=>"+1 671","code"=>"GU"],
                ["name"=>"Guatemala","mobile_code"=>"+502","code"=>"GT"],
                ["name"=>"Guernsey","mobile_code"=>"+44","code"=>"GG"],
                ["name"=>"Guinea","mobile_code"=>"+224","code"=>"GN"],
                ["name"=>"Guinea-Bissau","mobile_code"=>"+245","code"=>"GW"],
                ["name"=>"Guyana","mobile_code"=>"+595","code"=>"GY"],
                ["name"=>"Haiti","mobile_code"=>"+509","code"=>"HT"],
                ["name"=>"Holy See (Vatican City State)","mobile_code"=>"+379","code"=>"VA"],
                ["name"=>"Honduras","mobile_code"=>"+504","code"=>"HN"],
                ["name"=>"Hong Kong","mobile_code"=>"+852","code"=>"HK"],
                ["name"=>"Hungary","mobile_code"=>"+36","code"=>"HU"],
                ["name"=>"Iceland","mobile_code"=>"+354","code"=>"IS"],
                ["name"=>"India","mobile_code"=>"+91","code"=>"IN"],
                ["name"=>"Indonesia","mobile_code"=>"+62","code"=>"ID"],
                ["name"=>"Iran, Islamic Republic of","mobile_code"=>"+98","code"=>"IR"],
                ["name"=>"Iraq","mobile_code"=>"+964","code"=>"IQ"],
                ["name"=>"Ireland","mobile_code"=>"+353","code"=>"IE"],
                ["name"=>"Isle of Man","mobile_code"=>"+44","code"=>"IM"],
                ["name"=>"Israel","mobile_code"=>"+972","code"=>"IL"],
                ["name"=>"Italy","mobile_code"=>"+39","code"=>"IT"],
                ["name"=>"Jamaica","mobile_code"=>"+1 876","code"=>"JM"],
                ["name"=>"Japan","mobile_code"=>"+81","code"=>"JP"],
                ["name"=>"Jersey","mobile_code"=>"+44","code"=>"JE"],
                ["name"=>"Jordan","mobile_code"=>"+962","code"=>"JO"],
                ["name"=>"Kazakhstan","mobile_code"=>"+7 7","code"=>"KZ"],
                ["name"=>"Kenya","mobile_code"=>"+254","code"=>"KE"],
                ["name"=>"Kiribati","mobile_code"=>"+686","code"=>"KI"],
                ["name"=>"Korea, Democratic People\"s Republic of","mobile_code"=>"+850","code"=>"KP"],
                ["name"=>"Korea, Republic of","mobile_code"=>"+82","code"=>"KR"],
                ["name"=>"Kuwait","mobile_code"=>"+965","code"=>"KW"],
                ["name"=>"Kyrgyzstan","mobile_code"=>"+996","code"=>"KG"],
                ["name"=>"Lao People\"s Democratic Republic","mobile_code"=>"+856","code"=>"LA"],
                ["name"=>"Latvia","mobile_code"=>"+371","code"=>"LV"],
                ["name"=>"Lebanon","mobile_code"=>"+961","code"=>"LB"],
                ["name"=>"Lesotho","mobile_code"=>"+266","code"=>"LS"],
                ["name"=>"Liberia","mobile_code"=>"+231","code"=>"LR"],
                ["name"=>"Libyan Arab Jamahiriya","mobile_code"=>"+218","code"=>"LY"],
                ["name"=>"Liechtenstein","mobile_code"=>"+423","code"=>"LI"],
                ["name"=>"Lithuania","mobile_code"=>"+370","code"=>"LT"],
                ["name"=>"Luxembourg","mobile_code"=>"+352","code"=>"LU"],
                ["name"=>"Macao","mobile_code"=>"+853","code"=>"MO"],
                ["name"=>"Macedonia, The Former Yugoslav Republic of","mobile_code"=>"+389","code"=>"MK"],
                ["name"=>"Madagascar","mobile_code"=>"+261","code"=>"MG"],
                ["name"=>"Malawi","mobile_code"=>"+265","code"=>"MW"],
                ["name"=>"Malaysia","mobile_code"=>"+60","code"=>"MY"],
                ["name"=>"Maldives","mobile_code"=>"+960","code"=>"MV"],
                ["name"=>"Mali","mobile_code"=>"+223","code"=>"ML"],
                ["name"=>"Malta","mobile_code"=>"+356","code"=>"MT"],
                ["name"=>"Marshall Islands","mobile_code"=>"+692","code"=>"MH"],
                ["name"=>"Martinique","mobile_code"=>"+596","code"=>"MQ"],
                ["name"=>"Mauritania","mobile_code"=>"+222","code"=>"MR"],
                ["name"=>"Mauritius","mobile_code"=>"+230","code"=>"MU"],
                ["name"=>"Mayotte","mobile_code"=>"+262","code"=>"YT"],
                ["name"=>"Mexico","mobile_code"=>"+52","code"=>"MX"],
                ["name"=>"Micronesia, Federated States of","mobile_code"=>"+691","code"=>"FM"],
                ["name"=>"Moldova, Republic of","mobile_code"=>"+373","code"=>"MD"],
                ["name"=>"Monaco","mobile_code"=>"+377","code"=>"MC"],
                ["name"=>"Mongolia","mobile_code"=>"+976","code"=>"MN"],
                ["name"=>"Montenegro","mobile_code"=>"+382","code"=>"ME"],
                ["name"=>"Montserrat","mobile_code"=>"+1664","code"=>"MS"],
                ["name"=>"Morocco","mobile_code"=>"+212","code"=>"MA"],
                ["name"=>"Mozambique","mobile_code"=>"+258","code"=>"MZ"],
                ["name"=>"Myanmar","mobile_code"=>"+95","code"=>"MM"],
                ["name"=>"Namibia","mobile_code"=>"+264","code"=>"NA"],
                ["name"=>"Nauru","mobile_code"=>"+674","code"=>"NR"],
                ["name"=>"Nepal","mobile_code"=>"+977","code"=>"NP"],
                ["name"=>"Netherlands","mobile_code"=>"+31","code"=>"NL"],
                ["name"=>"Netherlands Antilles","mobile_code"=>"+599","code"=>"AN"],
                ["name"=>"New Caledonia","mobile_code"=>"+687","code"=>"NC"],
                ["name"=>"New Zealand","mobile_code"=>"+64","code"=>"NZ"],
                ["name"=>"Nicaragua","mobile_code"=>"+505","code"=>"NI"],
                ["name"=>"Niger","mobile_code"=>"+227","code"=>"NE"],
                ["name"=>"Nigeria","mobile_code"=>"+234","code"=>"NG"],
                ["name"=>"Niue","mobile_code"=>"+683","code"=>"NU"],
                ["name"=>"Norfolk Island","mobile_code"=>"+672","code"=>"NF"],
                ["name"=>"Northern Mariana Islands","mobile_code"=>"+1 670","code"=>"MP"],
                ["name"=>"Norway","mobile_code"=>"+47","code"=>"NO"],
                ["name"=>"Oman","mobile_code"=>"+968","code"=>"OM"],
                ["name"=>"Pakistan","mobile_code"=>"+92","code"=>"PK"],
                ["name"=>"Palau","mobile_code"=>"+680","code"=>"PW"],
                ["name"=>"Palestinian Territory, Occupied","mobile_code"=>"+970","code"=>"PS"],
                ["name"=>"Panama","mobile_code"=>"+507","code"=>"PA"],
                ["name"=>"Papua New Guinea","mobile_code"=>"+675","code"=>"PG"],
                ["name"=>"Paraguay","mobile_code"=>"+595","code"=>"PY"],
                ["name"=>"Peru","mobile_code"=>"+51","code"=>"PE"],
                ["name"=>"Philippines","mobile_code"=>"+63","code"=>"PH"],
                ["name"=>"Pitcairn","mobile_code"=>"+872","code"=>"PN"],
                ["name"=>"Poland","mobile_code"=>"+48","code"=>"PL"],
                ["name"=>"Portugal","mobile_code"=>"+351","code"=>"PT"],
                ["name"=>"Puerto Rico","mobile_code"=>"+1 939","code"=>"PR"],
                ["name"=>"Qatar","mobile_code"=>"+974","code"=>"QA"],
                ["name"=>"Romania","mobile_code"=>"+40","code"=>"RO"],
                ["name"=>"Russia","mobile_code"=>"+7","code"=>"RU"],
                ["name"=>"Rwanda","mobile_code"=>"+250","code"=>"RW"],
                ["name"=>"Réunion","mobile_code"=>"+262","code"=>"RE"],
                ["name"=>"Saint Barthélemy","mobile_code"=>"+590","code"=>"BL"],
                ["name"=>"Saint Helena, Ascension and Tristan Da Cunha","mobile_code"=>"+290","code"=>"SH"],
                ["name"=>"Saint Kitts and Nevis","mobile_code"=>"+1 869","code"=>"KN"],
                ["name"=>"Saint Lucia","mobile_code"=>"+1 758","code"=>"LC"],
                ["name"=>"Saint Martin","mobile_code"=>"+590","code"=>"MF"],
                ["name"=>"Saint Pierre and Miquelon","mobile_code"=>"+508","code"=>"PM"],
                ["name"=>"Saint Vincent and the Grenadines","mobile_code"=>"+1 784","code"=>"VC"],
                ["name"=>"Samoa","mobile_code"=>"+685","code"=>"WS"],
                ["name"=>"San Marino","mobile_code"=>"+378","code"=>"SM"],
                ["name"=>"Sao Tome and Principe","mobile_code"=>"+239","code"=>"ST"],
                ["name"=>"Saudi Arabia","mobile_code"=>"+966","code"=>"SA"],
                ["name"=>"Senegal","mobile_code"=>"+221","code"=>"SN"],
                ["name"=>"Serbia","mobile_code"=>"+381","code"=>"RS"],
                ["name"=>"Seychelles","mobile_code"=>"+248","code"=>"SC"],
                ["name"=>"Sierra Leone","mobile_code"=>"+232","code"=>"SL"],
                ["name"=>"Singapore","mobile_code"=>"+65","code"=>"SG"],
                ["name"=>"Slovakia","mobile_code"=>"+421","code"=>"SK"],
                ["name"=>"Slovenia","mobile_code"=>"+386","code"=>"SI"],
                ["name"=>"Solomon Islands","mobile_code"=>"+677","code"=>"SB"],
                ["name"=>"Somalia","mobile_code"=>"+252","code"=>"SO"],
                ["name"=>"South Africa","mobile_code"=>"+27","code"=>"ZA"],
                ["name"=>"South Georgia and the South Sandwich Islands","mobile_code"=>"+500","code"=>"GS"],
                ["name"=>"Spain","mobile_code"=>"+34","code"=>"ES"],
                ["name"=>"Sri Lanka","mobile_code"=>"+94","code"=>"LK"],
                ["name"=>"Sudan","mobile_code"=>"+249","code"=>"SD"],
                ["name"=>"Suriname","mobile_code"=>"+597","code"=>"SR"],
                ["name"=>"Svalbard and Jan Mayen","mobile_code"=>"+47","code"=>"SJ"],
                ["name"=>"Swaziland","mobile_code"=>"+268","code"=>"SZ"],
                ["name"=>"Sweden","mobile_code"=>"+46","code"=>"SE"],
                ["name"=>"Switzerland","mobile_code"=>"+41","code"=>"CH"],
                ["name"=>"Syrian Arab Republic","mobile_code"=>"+963","code"=>"SY"],
                ["name"=>"Taiwan","mobile_code"=>"+886","code"=>"TW"],
                ["name"=>"Tajikistan","mobile_code"=>"+992","code"=>"TJ"],
                ["name"=>"Tanzania, United Republic of","mobile_code"=>"+255","code"=>"TZ"],
                ["name"=>"Thailand","mobile_code"=>"+66","code"=>"TH"],
                ["name"=>"Timor-Leste","mobile_code"=>"+670","code"=>"TL"],
                ["name"=>"Togo","mobile_code"=>"+228","code"=>"TG"],
                ["name"=>"Tokelau","mobile_code"=>"+690","code"=>"TK"],
                ["name"=>"Tonga","mobile_code"=>"+676","code"=>"TO"],
                ["name"=>"Trinidad and Tobago","mobile_code"=>"+1 868","code"=>"TT"],
                ["name"=>"Tunisia","mobile_code"=>"+216","code"=>"TN"],
                ["name"=>"Turkey","mobile_code"=>"+90","code"=>"TR"],
                ["name"=>"Turkmenistan","mobile_code"=>"+993","code"=>"TM"],
                ["name"=>"Turks and Caicos Islands","mobile_code"=>"+1 649","code"=>"TC"],
                ["name"=>"Tuvalu","mobile_code"=>"+688","code"=>"TV"],
                ["name"=>"Uganda","mobile_code"=>"+256","code"=>"UG"],
                ["name"=>"Ukraine","mobile_code"=>"+380","code"=>"UA"],
                ["name"=>"United Arab Emirates","mobile_code"=>"+971","code"=>"AE"],
                ["name"=>"United Kingdom","mobile_code"=>"+44","code"=>"GB"],
                ["name"=>"United States","mobile_code"=>"+1","code"=>"US"],
                ["name"=>"Uruguay","mobile_code"=>"+598","code"=>"UY"],
                ["name"=>"Uzbekistan","mobile_code"=>"+998","code"=>"UZ"],
                ["name"=>"Vanuatu","mobile_code"=>"+678","code"=>"VU"],
                ["name"=>"Venezuela, Bolivarian Republic of","mobile_code"=>"+58","code"=>"VE"],
                ["name"=>"Viet Nam","mobile_code"=>"+84","code"=>"VN"],
                ["name"=>"Virgin Islands, British","mobile_code"=>"+1 284","code"=>"VG"],
                ["name"=>"Virgin Islands, U.S.","mobile_code"=>"+1 340","code"=>"VI"],
                ["name"=>"Wallis and Futuna","mobile_code"=>"+681","code"=>"WF"],
                ["name"=>"Yemen","mobile_code"=>"+967","code"=>"YE"],
                ["name"=>"Zambia","mobile_code"=>"+260","code" => "ZM"],
                ["name"=>"Zimbabwe","mobile_code"=>"+263","code"=>"ZW"],
                ["name"=>"Åland Islands","mobile_code"=>"+358","code"=>"AX"]
            ];
            Schema::create("countries", function (Blueprint $table) {
                $table->increments('id');
                $table->string("name");
                $table->string("mobile_code");
                $table->string("code");
                $table->string("flag")->nullable();
            });
            Country::insert($countryJson);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}
